### ISSUE TITLE
Setup using CLI starter kit is broken by Github SSH key issue

### ISSUE THREAD

**Issue by sdk451** [apptension/saas-boilerplate#263]
**Describe the bug**
Attempted to use the Starter kit CLI command "npm init saas-boilerplate" to start a new clone of the project, but it failed with the error message from my terminal log:

npm init saas-boilerplate
Performing system check:
√ Checking if docker is installed... it is!
√ Checking if pnpm is installed... it is!
√ Checking if nx is installed... it is!
Project will be initialized in directory: C:\saas-demo
Fetching latest release... done
Latest release: 2.0.0-alpha.1
Start cloning repository... !
    Error: Cloning into 'C:\saas-demo'...
    Host key verification failed.
    fatal: Could not read from remote repository.

I believe this is because Github changed their public SSH key - see here 
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**To Reproduce**
run the start kit CLI command "npm init saas-boilerplate"

**Expected behavior**
we get a configured and working clone of the repo

**Comment by mkleszcz** [comment]
Hi @sdk451,

Thank you for reporting this issue. The error message you're encountering seems to be related to SSH key verification, which is usually a part of the local git or ssh configuration on your machine, rather than an error within the `create-saas-boilerplate` script. This script doesn't include any built-in git client and relies on the git installation on your local environment.

As a first step to troubleshoot this issue, could you please try to manually clone the repository using the git clone command in your terminal and let us know if it works? This would help us determine where the issue is.

**Comment by sdk451** [comment]
I can clone the repo manually. I've done that and been working through the installation (stuck on the "nx run core:docker-compose:up" at the moment - pnpm nx docker-create-volumes is exiting with non-zero code, but I'll just work through that  - I'm sure its a config issue at my end).

When I had a look at the log of the CLI command "npm init saas-boilerplate" command,  I can see the npm init registry script contains an ssh key for github. I suspect this what is failing, and where the host key verification failed message arises.

**Comment by sdk451** [comment]
Unfortunately didn’t work. I’ll have a look at the logs.
