### ISSUE TITLE
Bad Gateway 

### ISSUE THREAD

**Issue by rahuliitk** [apptension/saas-boilerplate#314]
**Describe the bug**
Inspite of running the installation several times and all modules installed still it's showing 502 Bad Gateway

**To Reproduce**
1. Install as per your instructions without filling any other env variable or giving it google/facebook auth
2. Click on localhost:3000 and other backend ports which get opened
3. See error. I have attached all screenshots

**Expected behavior**
I want all the ports to display as is given in documentation like : signup page, admin page, etc
**Screenshots**

**Desktop (please complete the following information):**
 I am running this in Github codespace

**Smartphone (please complete the following information):**
Github Codespace, Chrome, Windows local machine

**Additional context**
<img width="960" alt="Screenshot 2023-07-03 230501" src="https://github.com/apptension/saas-boilerplate/assets/1323845/3c55f4e1-6c73-4b68-bfbd-2815655a1f3e">
<img width="598" alt="Screenshot 2023-07-03 230548" src="https://github.com/apptension/saas-boilerplate/assets/1323845/3f17d471-86e1-4824-8370-76b71a23d4f4">
<img width="952" alt="Screenshot 2023-07-03 230556" src="https://github.com/apptension/saas-boilerplate/assets/1323845/5680c73b-5890-407c-90f3-0e9ddfd9ff90">
<img width="928" alt="Screenshot 2023-07-03 230605" src="https://github.com/apptension/saas-boilerplate/assets/1323845/61490e0f-14bd-4191-80d1-a7520d45006b">
<img width="958" alt="Screenshot 2023-07-03 230618" src="https://github.com/apptension/saas-boilerplate/assets/1323845/f61e2481-9be2-4f09-9feb-028f2699d1b5">
<img width="949" alt="Screenshot 2023-07-03 230631" src="https://github.com/apptension/saas-boilerplate/assets/1323845/4204eaba-4fa7-40bd-9711-19e737950a0b">
<img width="956" alt="Screenshot 2023-07-03 230642" src="https://github.com/apptension/saas-boilerplate/assets/1323845/9bdbda2c-c936-46df-ad3b-d3957abc3d75">
<img width="958" alt="Screenshot 2023-07-03 230654" src="https://github.com/apptension/saas-boilerplate/assets/1323845/9d494bed-3991-4682-a2d6-6182395c514f">
<img width="958" alt="Screenshot 2023-07-03 230702" src="https://github.com/apptension/saas-boilerplate/assets/1323845/4c5fa377-f648-4e29-bf27-d279c47ff34e">
<img width="960" alt="Screenshot 2023-07-03 230713" src="https://github.com/apptension/saas-boilerplate/assets/1323845/95f9cdc9-73aa-4c42-a05e-2a62603311d0">
<img width="945" alt="Screenshot 2023-07-03 230722" src="https://github.com/apptension/saas-boilerplate/assets/1323845/468fd998-9612-4a08-8c51-cf81c9c92737">
<img width="954" alt="Screenshot 2023-07-03 230730" src="https://github.com/apptension/saas-boilerplate/assets/1323845/572eda68-ffb8-4582-ade1-21ba28d4ac4c">

**Comment by mkleszcz** [comment]
Dear @rahuliitk,

It seems like the 502 Bad Gateway errors you're experiencing are a result of an invalid proxy configuration. Github Codespaces, by design, maps each port with an active listening process to a subdomain. In our case, servers like `vite` expect to listen on the `localhost` host, rather than `0.0.0.0`, which could be the root cause of the 502 error you're seeing.

Here's what you can do to change the server configuration:

1. Navigate to `packages/webapp/vite.config.ts`
2. Change host to `0.0.0.0`
3. You can find and modify the `VITE_BASE_API_URL` environment variable in the `packages/webapp/.env` file to the correct API URL in the codespace

However, please note that even after making these changes, you might still face several issues. One of them is CORS (Cross-Origin Resource Sharing) errors, which could prevent the app from working correctly. Additionally, hot module replacement (HMR) might not function as expected, causing further difficulties.

It's also worth noting that our SaaS Boilerplate is not designed or tested to work in environments like Github Codespaces. It is primarily designed to be set up and run in development mode locally on a machine.

We recommend setting up the project locally and testing it on your local machine. This would offer a more streamlined and consistent experience and should help you avoid the aforementioned issues.
