### ISSUE TITLE
Fresh project pre-commit issue

### ISSUE THREAD

**Issue by matiasanaya** [apptension/saas-boilerplate#446]
### Documentation is

- [X] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in detail

I ran `pnpm create saas-boilerplate .` and the immediately tried to run `git commit -m "boilerplate: init saas-boilerplate"` which failed with:

```
 Running pre-commit tasks 🚀
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ .lintstagedrc — 932 files (chunk 1/2)...
    ❯ *.{ts,tsx} — 343 files
      ✖ eslint --fix [FAILED]
    ❯ *.{json,md,html} — 95 files
      ✖ prettier --write [KILLED]
  ❯ .lintstagedrc — 931 files (chunk 2/2)...
    ❯ *.{ts,tsx} — 680 files
      ✖ eslint --fix [KILLED]
    ❯ *.{json,md,html} — 58 files
      ✖ prettier --write [KILLED]
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --fix:

Oops! Something went wrong! :(

...

husky - pre-commit hook exited with code 1 (error)
``` 

This can be fixed by running `pnpm nx start webapp`, maybe running `pnpm install`?

### Your Suggestion for Changes

I'd suggest documenting this. At least for me is natural to commit the boilerplate starting state before running anything else.

**Comment by mkleszcz** [comment]
The issue is caused by: https://github.com/nrwl/nx/issues/20752
Basically `@nx/enforce-module-boundaries` eslint plugin throws an error when there is no NX graph generated. Starting webapp before first commit will call under the hood NX and generate the graph, this is why it's working after.
It can be fixed also by calling other NX command, like: `pnpm nx show projects`.
